service:
  name: "zcloud"
  local: true
  remote:
    host: "192.168.1.100"
    port: 22
    user: "deployuser"
    password: "password"
  install_package: "./services/zcloud/install.tar.gz"
  upgrade_package: "./services/zcloud/upgrade.tar.gz"
  install_script: "./services/zcloud/install.sh"
  backup_script: "./services/zcloud/backup.sh"
  rollback_script: "./services/zcloud/rollback.url"
  check_health_script: "./services/zcloud/check_health_script.sh"
  upgrade_script: "./services/zcloud/upgrade.py"
  change_ip_script: "./services/zcloud/change_ip.sh"
  install_path: "/opt/zcloud"
  start_command: "systemctl start zcloud"
  stop_command: "systemctl stop zcloud"
  priority: 2 # 低数字优先执行