global_vars:
  host: localhost
  port: 5432
  user: dbuser
  password: dbpass
  endpoint: https://api.example.com
  timeout: 30
  mysqluser: root
  mysqlpassword: 123456
  mysqlhost: 192.168.48.154
  mysqlhostport: 3306
  install_path: "/opt/dbaas"
  mysql_password: dbaas@123
  outsidePrometheus: 0
  defaultCoreNum: 16
  diskCapacity: 20
  defaultMemorySize: 30
  installNodeType: OneNode
  theme: ""