nodes:
  - name: "node1"
    host: "172.20.23.111"
    port: 22
    user: "root"
    password: "Enmotech@2025"


services:
  - name: "zcloud"
    local: true
    priority: 1 # 低数字优先执行
    pre_check_scripts:
      - "./script/env_check/checkCpuCore.sh"
      - "./script/env_check/checkDirExist.sh"
      - "./script/env_check/checkDiskCapacity.sh"
      - "./script/env_check/checkMemory.sh"
      - "./script/env_check/checkTimeZone.sh"
      - "./script/env_check/checkZcloudVersion.sh"
    env_init_scripts: #需要顺序执行
      - "./script/env_init/authLicence.sh"
      - "./script/env_init/configSysParam.sh"
      - "./script/env_init/createDir.sh"
      - "./script/env_init/creatUser.sh"
      - "./script/env_init/installDependence.sh"
      - "./script/env_init/authInstallPackage.sh"
      - "./script/env_init/movePubLib.sh"
      - "./script/env_init/initCurrentCfg.sh"
#      - "./script/env_init/copyPackage.sh"

#  - name: "jdk"
#    local: false
#    remote_name: "node1"
#    pkg_copy_map: #拷包示例：当前资源路径、目标主机路径
#      soft/java: "~/zcloud/soft/java"
#    priority: 2 # 低数字优先执行

  - name: "jdk"
    local: true
    priority: 2 # 低数字优先执行

  - name: "lowcode"
    local: true
    priority: 2

  - name: "nginx"
    local: true
    priority: 2 # 低数字优先执行

  - name: "mysql"
    local: true
    priority: 2 # 低数字优先执行

  - name: "keeper"
    local: true
    priority: 2 # 低数字优先执行

  - name: "prometheus"
    local: true
    priority: 2 # 低数字优先执行

  - name: "consul"
    local: true
    priority: 2 # 低数字优先执行

  - name: "zcloud_service"
    service_name: "dbaas-eureka-server"
    local: true
    priority: 2 # 低数字优先执行

  - name: "zcloud_service"
    service_name: "dbaas-flyway-manage"
    local: true
    priority: 2 # 低数字优先执行

  - name: "zcloud_service"
    service_name: "dbaas-infrastructure"
    local: true
    priority: 3 # 低数字优先执行

  - name: "zcloud_service"
    service_name: "dbaas-apigateway"
    local: true
    priority: 3 # 低数字优先执行

  - name: "zcloud_service"
    service_name: "dbaas-backend-mogdb"
    local: true
    priority: 3 # 低数字优先执行

  - name: "zcloud_service"
    service_name: "dbaas-backend-script"
    local: true
    priority: 3 # 低数字优先执行

  - name: "zcloud_service"
    service_name: "dbaas-common-backupcenter"
    local: true
    priority: 3 # 低数字优先执行

  - name: "zcloud_service"
    service_name: "dbaas-common-db"
    local: true
    priority: 3 # 低数字优先执行

  - name: "zcloud_service"
    service_name: "dbaas-database-snapshot"
    local: true
    priority: 3 # 低数字优先执行

  - name: "zcloud_service"
    service_name: "dbaas-db-manage"
    local: true
    priority: 3 # 低数字优先执行

#  - name: "zcloud_service"
#    service_name: "dbaas-doc-retrieval"
#    local: true
#    priority: 3 # 低数字优先执行

  - name: "zcloud_service"
    service_name: "dbaas-lowcode-atomic-ability"
    local: true
    priority: 3 # 低数字优先执行

#  - name: "zcloud_service"
#    service_name: "dbaas-lowcode-http-engine"
#    local: true
#    priority: 3 # 低数字优先执行

  - name: "zcloud_service"
    service_name: "dbaas-management-database"
    local: true
    priority: 3 # 低数字优先执行

  - name: "zcloud_service"
    service_name: "dbaas-management-host"
    local: true
    priority: 3 # 低数字优先执行

  - name: "zcloud_service"
    service_name: "dbaas-mariadb"
    local: true
    priority: 3 # 低数字优先执行

  - name: "zcloud_service"
    service_name: "dbaas-monitor"
    local: true
    priority: 3 # 低数字优先执行

  - name: "zcloud_service"
    service_name: "dbaas-ogg-management"
    local: true
    priority: 3 # 低数字优先执行

  - name: "zcloud_service"
    service_name: "dbaas-permissions"
    local: true
    priority: 3 # 低数字优先执行

  - name: "zcloud_service"
    service_name: "dbaas-reposerver"
    local: true
    priority: 3 # 低数字优先执行

  - name: "zcloud_service"
    service_name: "task-management"
    local: true
    priority: 3 # 低数字优先执行

  - name: "zcloud_service"
    service_name: "zdbmon-mgr"
    local: true
    priority: 3 # 低数字优先执行

  - name: "zcloud_service"
    service_name: "lowcode"
    local: true
    priority: 3 # 低数字优先执行

#  - name: "exportKnwlBase"
#    local: true
#    priority: 3 # 低数字优先执行

  - name: "proxy"
    local: true
    priority: 3 # 低数字优先执行

  - name: "zcloud_service"
    service_name: "node-exporter"
    local: true
    priority: 3 # 低数字优先执行

  - name: "zcloud_service"
    service_name: "alertmanager"
    local: true
    priority: 3 # 低数字优先执行

  - name: "zcloud_service"
    service_name: "zoramon-mgr"
    local: true
    priority: 3 # 低数字优先执行

  - name: "zcloud_service"
    service_name: "smart-baseline"
    local: true
    priority: 3 # 低数字优先执行

  - name: "zcloud_service"
    service_name: "dbaas-mail-sender"
    local: true
    priority: 3 # 低数字优先执行

  - name: "zcloud_service"
    service_name: "dbaas-wxwork-sender"
    local: true
    priority: 3 # 低数字优先执行

  - name: "zcloud_service"
    service_name: "dbaas-sender-common"
    local: true
    priority: 3 # 低数字优先执行

  - name: "zcloud_service"
    service_name: "dbaas-zabbix-sender"
    local: true
    priority: 3 # 低数字优先执行



#  - name: "backup"
#    local: true
#    priority: 2 # 低数字优先执行
#  - name: "java-service"
#    local: true
#    service_name: "apiGateWay"
#    priority: 2 # 低数字优先执行

#  - name: "keeper"
#    local: true
#    priority: 2 # 低数字优先执行
#





#  - name: "mogdb"
#    local: false
#    remote_name: "node1"
#    pkg_copy_map: #拷包示例：当前资源路径、目标主机路径
#      - soft/mogdb: "soft/mogdb"
#    priority: 2 # 低数字优先执行

#  - name: "mysql"
#    local: true
#    remote:
#      host: "192.168.48.174"
#      port: 22
#      user: "root"
#      password: "root@123"
#    install_path: "/opt/dbaas"
#    priority: 2 # 低数字优先执行

#  - name: "consul"
#    local: true
#    remote:
#      host: "192.168.48.174"
#      port: 22
#      user: "root"
#      password: "root@123"
#    install_path: "/opt/dbaas"
#    priority: 2 # 低数字优先执行



