sourceLimit:
  cpuUsagePercentage: 85 #unit %
  memoryUsagePercentage: 85 # unit %
  memoryMinimumValue: 7 # os memory minimum value unit GB
  freeDiskSpace: 5 # unit GB
  dataStoragePath: "/home/zcloud"
log:
  level: debug